### ISSUE TITLE
有问题需要请教

### ISSUE THREAD

**Issue by Fimwu7** [ingra14m/GraduationProject#1]
你好，请问该项目的运行效果是什么样的呢
我在运行时会出现以下错误，请问可以帮忙解答下吗 不胜感激
D:\GP\GraduationProject-main\src\utils\FocalLoss.py:43: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  P = F.softmax(inputs)
Traceback (most recent call last):
  File "D:/GP/GraduationProject-main/src/main.py", line 183, in <module>
    train(model=model, optimizer=optimizer, graph=graph, output=args.output)
  File "D:/GP/GraduationProject-main/src/main.py", line 61, in train
    loss = loss_function(pred[graph.edata['train_mask']], edata_label[graph.edata['train_mask']])
  File "C:\Users\BinQiang Zhang\.conda\envs\Sum\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\GP\GraduationProject-main\src\utils\FocalLoss.py", line 48, in forward
    class_mask.scatter_(1, ids.data, 1.)
RuntimeError: scatter(): Expected dtype int64 for index

**Comment by ingra14m** [comment]
这个很有可能是因为操作系统或者torch版本对于默认tensor类型不一致导致。可以显式指定一开始tensor的类型。当然最快速的解决方案应该是将src中的main函数中的第61行替换为CE损失函数。
```python
loss = F.cross_entropy(pred[graph.edata['train_mask']], edata_label[graph.edata['train_mask']])
```

经过实践，在这个DDI问题的数据集中，focal与CE差别不大

**Comment by Fimwu7** [comment]
谢谢学长的答复，请问学长有相应的关于该代码的论文参考吗。

**Comment by ingra14m** [comment]
这个代码就是图神经网络的边分类问题，图网络特征提取器 + MLP分类器，DDI相关的方面参考价值不大，就是提供了一个数据而已～
- GCN：https://arxiv.org/pdf/1609.02907.pdf
- GAT：https://arxiv.org/abs/1710.10903
- GraphSAGE：https://arxiv.org/abs/1706.02216
- GateGAT：这个是自己搭的，没有直接的论文，但是核心是在GAT的基础上加上门控机制，去除掉一些没有用的边

其他我认为可能会有帮助的：
- dgl：图神经网络的框架，类似pytorch基于python
- 我学长的论文：https://pubmed.ncbi.nlm.nih.gov/34671814/
    - 数据集的处理和focal loss function的灵感源于这里

**Comment by Fimwu7** [comment]
学长，真真真最后一个问题，
![image](https://user-images.githubusercontent.com/101780192/168798410-60843a81-25e7-4987-b8be-7ca09b8edea2.png)
就是您的这个数据的目录下CSV文件有两个（因为没有drugbank的下载权限）所以并不是很了解这两个数据集中的clean<50和noddi<50又是什么意思呢？
一个正在学习图神经网络的萌新。
非常感谢学长的回复，
非常感谢。

**Comment by ingra14m** [comment]
这两个csv的信息都可以在db中找到，其实没有什么用 \doge
对于drugbank，其实我几乎没打开过 \doge
我这个工程更侧重网络模型的搭建，drugbank中每一项的意义我也没有研究过。
如果你对于数据有一些疑问，你不妨可以看一下src/utils中的PreProcessing.py，通过看如何处理数据你就会明白这些特征具体是怎么利用的了

**Comment by Fimwu7** [comment]
好的，感谢学长的倾囊相授。
再次感谢学长，祝你学业有成，前途似锦。
